package com.wipro.pizza_order_service.controller;

import com.wipro.pizza_order_service.dto.OrderRequest;
import com.wipro.pizza_order_service.model.Order;
import com.wipro.pizza_order_service.service.OrderService;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;


@RestController
@RequestMapping("/api/orders") // Base URL for all order related APIs
public class OrderController {

    @Autowired
    private OrderService orderService; // Service layer that contains business logic


    // ===============================
    // CUSTOMER APIs
    // ===============================

    // Place a new order
    // Accessible only to users with CUSTOMER role
    // Order status will be set to PENDING initially
    @PostMapping
    @PreAuthorize("hasRole('CUSTOMER')")
    public Order placeOrder(@RequestBody OrderRequest request){
        return orderService.placeOrder(request);
    }


    // Get orders of a specific user by email
    // Used in "My Orders" page in the frontend
    @GetMapping("/user/{email}")
    @PreAuthorize("hasRole('CUSTOMER')")
    public List<Order> getUserOrders(@PathVariable String email){
        return orderService.getOrdersByUser(email);
    }


    // ===============================
    // ADMIN APIs
    // ===============================

    // Get all orders (for admin dashboard)
    @GetMapping("/all")
    @PreAuthorize("hasRole('ADMIN')")
    public List<Order> getAllOrders(){
        return orderService.getAllOrders();
    }


    // Get only PENDING orders
    // Used by admin to approve or process orders
    @GetMapping("/pending")
    @PreAuthorize("hasRole('ADMIN')")
    public List<Order> getPendingOrders(){
        return orderService.getPendingOrders();
    }


    // Update order status
    // Example: PUT /api/orders/5/status?status=PREPARING
    // Only ADMIN can update order status
    @PutMapping("/{orderId}/status")
    @PreAuthorize("hasRole('ADMIN')")
    public Order updateStatus(@PathVariable Long orderId,
                              @RequestParam String status){

        return orderService.updateOrderStatus(orderId, status);
    }


    // ===============================
    // REPORT APIs (Admin Dashboard)
    // ===============================

    // Get today's total sales amount
    @GetMapping("/reports/daily-sales")
    @PreAuthorize("hasRole('ADMIN')")
    public Double getDailySales(){
        return orderService.getDailySales();
    }


    // Get monthly sales report
    // Returns month number and total sales
    @GetMapping("/reports/monthly-sales")
    @PreAuthorize("hasRole('ADMIN')")
    public List<Object[]> getMonthlySales(){
        return orderService.getMonthlySales();
    }


    // Get total revenue generated by the system
    @GetMapping("/reports/revenue")
    @PreAuthorize("hasRole('ADMIN')")
    public Double getTotalRevenue(){
        return orderService.getTotalRevenue();
    }


    // Get order trends (number of orders per day)
    @GetMapping("/reports/order-trends")
    @PreAuthorize("hasRole('ADMIN')")
    public List<Object[]> getOrderTrends(){
        return orderService.getOrderTrends();
    }


    // Get top selling pizza based on quantity sold
    @GetMapping("/reports/top-pizza")
    @PreAuthorize("hasRole('ADMIN')")
    public List<Object[]> getTopPizza(){
        return orderService.getTopSellingPizza();
    }

}